# Generated by Django 4.2.5 on 2023-10-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
